# Generated by Django 2.1.2 on 2019-07-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpi',
            name='cargarchivo',
            field=models.FileField(null=True, upload_to=None),
        ),
    ]
