# Generated by Django 2.1.2 on 2019-08-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0002_mpi_cargarchivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpi',
            name='cargarchivo',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
