# Generated by Django 2.1.2 on 2019-08-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0003_auto_20190802_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpi',
            name='cargarchivo',
            field=models.FileField(blank=True, null=True, upload_to='Descargas'),
        ),
    ]
