# Generated by Django 2.1.2 on 2019-08-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0004_auto_20190802_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpi',
            name='cargarchivo',
            field=models.FileField(blank=True, max_length=10, null=True, upload_to='misCargas/'),
        ),
    ]
