# Generated by Django 2.1.2 on 2019-08-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0006_auto_20190802_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpi',
            name='cargarchivo',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='misCargas'),
        ),
    ]
