# Generated by Django 2.1.2 on 2019-04-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio', models.IntegerField()),
                ('fechaAcutal', models.DateTimeField(auto_now_add=True)),
                ('apellidoNombre', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('coberturaMedica', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=20)),
                ('medico', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
                ('indicacion', models.CharField(max_length=50)),
                ('decubito', models.BooleanField()),
                ('pertimetroAbdominal', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('imc', models.IntegerField()),
                ('supCorporal', models.FloatField()),
                ('calidadTecnica', models.IntegerField()),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
