# Generated by Django 2.1.2 on 2019-04-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='decubito',
            field=models.CharField(max_length=50),
        ),
    ]
