from django.db import models
from core.models import Pacientes
# Create your models here.
class Mpi(models.Model):
    id_mpi = models.AutoField(primary_key=True)
    paciente_mpi = models.ForeignKey(Pacientes,null=True, on_delete=models.CASCADE)
    s1_rest = models.IntegerField(null=True)
    s2_rest = models.IntegerField(null=True)
    s3_rest = models.IntegerField(null=True)
    s4_rest = models.IntegerField(null=True)
    s5_rest = models.IntegerField(null=True)
    s6_rest = models.IntegerField(null=True)
    s7_rest = models.IntegerField(null=True)
    s8_rest = models.IntegerField(null=True)
    s9_rest = models.IntegerField(null=True)
    s10_rest = models.IntegerField(null=True)
    s11_rest = models.IntegerField(null=True)
    s12_rest = models.IntegerField(null=True)
    s13_rest = models.IntegerField(null=True)
    s14_rest = models.IntegerField(null=True)
    s15_rest = models.IntegerField(null=True)
    s16_rest = models.IntegerField(null=True)
    s17_rest = models.IntegerField(null=True)
#fin rest
    s1_stress = models.IntegerField(null=True)
    s2_stress = models.IntegerField(null=True)
    s3_stress = models.IntegerField(null=True)
    s4_stress = models.IntegerField(null=True)
    s5_stress = models.IntegerField(null=True)
    s6_stress = models.IntegerField(null=True)
    s7_stress = models.IntegerField(null=True)
    s8_stress = models.IntegerField(null=True)
    s9_stress = models.IntegerField(null=True)
    s10_stress = models.IntegerField(null=True)
    s11_stress = models.IntegerField(null=True)
    s12_stress = models.IntegerField(null=True)
    s13_stress = models.IntegerField(null=True)
    s14_stress = models.IntegerField(null=True)
    s15_stress = models.IntegerField(null=True)
    s16_stress = models.IntegerField(null=True)
    s17_stress = models.IntegerField(null=True)
#fin stress
    s1_dif = models.IntegerField(null=True)
    s2_dif = models.IntegerField(null=True)
    s3_dif = models.IntegerField(null=True)
    s4_dif = models.IntegerField(null=True)
    s5_dif = models.IntegerField(null=True)
    s6_dif = models.IntegerField(null=True)
    s7_dif = models.IntegerField(null=True)
    s8_dif = models.IntegerField(null=True)
    s9_dif = models.IntegerField(null=True)
    s10_dif = models.IntegerField(null=True)
    s11_dif = models.IntegerField(null=True)
    s12_dif = models.IntegerField(null=True)
    s13_dif = models.IntegerField(null=True)
    s14_dif = models.IntegerField(null=True)
    s15_dif = models.IntegerField(null=True)
    s16_dif = models.IntegerField(null=True)
    s17_dif = models.IntegerField(null=True)
#fin dif
    ssr=models.FloatField(null=True)
    sss=models.FloatField(null=True)
    ssd=models.FloatField(null=True)
    cargarchivo=models.FileField(upload_to="misCargas",max_length=150,null=True,blank=True)